Repository dart-lang/build, pull requests merged in 2018-03, with the labels that each got.

#1068 Add nicer missing module reporting
  build_modules/CHANGELOG.md
  build_modules/lib/build_modules.dart
  build_modules/lib/src/errors.dart
  build_modules/lib/src/modules.dart
  build_modules/lib/src/summary_builder.dart
  build_modules/pubspec.yaml
  build_modules/test/fixtures/a/lib/a_imports_b_no_cycle.dart
  build_modules/test/fixtures/b/lib/b_imports_a_no_cycle.dart
  build_modules/test/modules_test.dart
  build_modules/test/summary_builder_test.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/logging/build_for_input_logger.dart
  build_web_compilers/lib/src/dev_compiler_builder.dart
  build_web_compilers/lib/src/web_entrypoint_builder.dart
  build_web_compilers/pubspec.yaml
  build_web_compilers/test/dev_compiler_builder_test.dart
  e2e_example/pubspec.yaml
  e2e_example/test/serve_integration_test.dart
Labels: cla: yes

#1072 Allow same-package non-hidden to hidden reads
  build_runner/CHANGELOG.md
  build_runner/lib/src/asset/reader.dart
  build_runner/lib/src/build_script_generate/builder_ordering.dart
  build_runner/test/generate/build_test.dart
Labels: cla: yes

#1071 Add `applies_builders` configuration
  build_config/README.md
  build_config/lib/src/build_config.dart
  build_config/lib/src/parse.dart
  build_config/test/build_config_test.dart
  build_runner/CHANGELOG.md
  build_runner/lib/src/build_script_generate/build_script_generate.dart
  build_runner/lib/src/package_graph/apply_builders.dart
  build_runner/test/package_graph/apply_builders_test.dart
Labels: cla: yes

#1074 prepare packages for release
  build_config/pubspec.yaml
  build_modules/CHANGELOG.md
  build_modules/pubspec.yaml
  build_resolvers/CHANGELOG.md
  build_resolvers/pubspec.yaml
  build_runner/CHANGELOG.md
  build_runner/pubspec.yaml
  build_web_compilers/CHANGELOG.md
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1049 Add bazel_codegen to this repository.
  .travis.yml
  bazel_codegen/.mono_repo.yml
  bazel_codegen/CHANGELOG.md
  bazel_codegen/LICENSE
  bazel_codegen/lib/_bazel_codegen.dart
  bazel_codegen/lib/src/args/build_args.dart
  bazel_codegen/lib/src/args/builder_options.dart
  bazel_codegen/lib/src/args/startup_args.dart
  bazel_codegen/lib/src/assets/asset_filter.dart
  bazel_codegen/lib/src/assets/asset_reader.dart
  bazel_codegen/lib/src/assets/asset_writer.dart
  bazel_codegen/lib/src/assets/file_system.dart
  bazel_codegen/lib/src/assets/path_translation.dart
  bazel_codegen/lib/src/errors.dart
  bazel_codegen/lib/src/logging.dart
  bazel_codegen/lib/src/run_builders.dart
  bazel_codegen/lib/src/run_phases.dart
  bazel_codegen/lib/src/summaries/analysis_context.dart
  bazel_codegen/lib/src/summaries/arg_parser.dart
  bazel_codegen/lib/src/summaries/build_asset_uri_resolver.dart
  bazel_codegen/lib/src/summaries/resolvers.dart
  bazel_codegen/lib/src/summaries/summaries.dart
  bazel_codegen/lib/src/timing.dart
  bazel_codegen/pubspec.yaml
  bazel_codegen/test/asset_reader_test.dart
  bazel_codegen/test/file_system_test.dart
  bazel_codegen/test/logger_test.dart
  bazel_codegen/test/path_translation_test.dart
  bazel_codegen/test/run_builders_test.dart
  bazel_codegen/test/utils.dart
Labels: cla: yes

#1080 add e2e test that runs on latest raw release in cron jobs only
  .travis.yml
  bazel_codegen/lib/src/summaries/resolvers.dart
  bazel_codegen/pubspec.yaml
  build_resolvers/lib/src/resolver.dart
  build_resolvers/pubspec.yaml
  e2e_example/.mono_repo.yml
Labels: cla: yes

#1081 try adding an after_failure script that pings the build chat
  .travis.yml
  tool/report_failure.sh
Labels: cla: yes

#1082 skip stack trace test for now
  e2e_example/test/test_integration_test.dart
Labels: cla: yes

#1077 First start towards a post-build step
  build_config/CHANGELOG.md
  build_config/README.md
  build_config/lib/build_config.dart
  build_config/lib/src/build_config.dart
  build_config/lib/src/parse.dart
  build_config/pubspec.yaml
  build_config/test/build_config_test.dart
Labels: cla: yes

#1084 Filter inputs based on source assets
  build_runner/CHANGELOG.md
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/generate/input_matcher.dart
  build_runner/lib/src/generate/phase.dart
  build_runner/pubspec.yaml
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/generate/build_test.dart
Labels: cla: yes

#1099 e2e_example: Remove usage of pkg:browser
  e2e_example/pubspec.yaml
  e2e_example/web/index.html
  e2e_example/web/sub/index.html
Labels: cla: yes

#1094 Fix offset on null error
  build_modules/CHANGELOG.md
  build_modules/lib/src/errors.dart
  build_modules/pubspec.yaml
  build_modules/test/modules_test.dart
Labels: Type: bug, cla: yes

#1107 add support for --dump-info to dart2js
  build_web_compilers/CHANGELOG.md
  build_web_compilers/build.yaml
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/lib/src/web_entrypoint_builder.dart
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1106 add test that --define overrides build.yaml
  build_runner/test/generate/build_integration_test.dart
  e2e_example/test/dart2js_integration_test.dart
Labels: cla: yes

#1111 Merge master into dart2js-deferred-loading
  .travis.yml
  bazel_codegen/lib/src/summaries/resolvers.dart
  bazel_codegen/pubspec.yaml
  build_modules/CHANGELOG.md
  build_modules/lib/src/errors.dart
  build_modules/pubspec.yaml
  build_modules/test/modules_test.dart
  build_resolvers/lib/src/resolver.dart
  build_resolvers/pubspec.yaml
  build_runner/CHANGELOG.md
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/generate/input_matcher.dart
  build_runner/lib/src/generate/phase.dart
  build_runner/pubspec.yaml
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/generate/build_test.dart
  build_web_compilers/CHANGELOG.md
  build_web_compilers/build.yaml
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/lib/src/web_entrypoint_builder.dart
  build_web_compilers/pubspec.yaml
  e2e_example/.mono_repo.yml
  e2e_example/pubspec.yaml
  e2e_example/test/test_integration_test.dart
  e2e_example/web/index.html
  e2e_example/web/sub/index.html
  tool/report_failure.sh
Labels: cla: yes

#1101 Change or remove `text/javascript`
  build_runner/lib/src/server/graph_viz.html
  build_runner/lib/src/server/server.dart
  docs/getting_started.md
Labels: cla: yes

#1096 Only consider in-package nodes for outputsForPhase
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/generate/build_impl.dart
Labels: cla: yes

#1112 Add an issue template.
  .github/ISSUE_TEMPLATE.md
Labels: cla: yes

#1108 Add support for normalizing $default:$default
  build_config/CHANGELOG.md
  build_config/lib/src/key_normalization.dart
  build_config/test/build_config_test.dart
Labels: cla: yes

#1114 Update gitter badges
  build_modules/README.md
  build_runner/README.md
  build_test/README.md
  build_web_compilers/README.md
Labels: cla: yes

#1100 Use a 'builder label' for log messages
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/generate/phase.dart
  build_runner/lib/src/logging/build_for_input_logger.dart
  build_runner/lib/src/logging/std_io_logging.dart
  build_runner/lib/src/package_graph/apply_builders.dart
  build_runner/test/generate/build_integration_test.dart
  build_runner/test/generate/watch_integration_test.dart
  e2e_example/test/build_integration_test.dart
  e2e_example/test/common/utils.dart
Labels: cla: yes

#1110 Post process builder
  .travis.yml
  build_config/lib/src/build_config.dart
  build_config/lib/src/parse.dart
  build_config/test/build_config_test.dart
  build_runner/lib/src/asset/reader.dart
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/builder/post_process_builder.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1116 Support bootstrapping DDC for web workers
  build_web_compilers/CHANGELOG.md
  build_web_compilers/lib/src/dev_compiler_bootstrap.dart
  build_web_compilers/pubspec.yaml
Labels: cla: yes, package:build_web_compilers

#1119 Add support for IPv4 loopback
  build_runner/CHANGELOG.md
  build_runner/lib/src/entrypoint/options.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1120 Add some missing known logger names
  build_runner/lib/src/logging/std_io_logging.dart
Labels: cla: yes

#1126 dont use whereType
  build_modules/CHANGELOG.md
  build_modules/lib/src/errors.dart
  build_modules/pubspec.yaml
  build_modules/test/fixtures/a/lib/a_imports_b_no_cycle.dart
  build_modules/test/fixtures/a/lib/a_part_library_name.dart
  build_modules/test/modules_test.dart
Labels: cla: yes

#1118 Add PostProcessAction
  build_runner/CHANGELOG.md
  build_runner/lib/build_runner.dart
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/asset_graph/serialization.dart
  build_runner/lib/src/generate/build_definition.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/generate/create_merged_dir.dart
  build_runner/lib/src/generate/exceptions.dart
  build_runner/lib/src/generate/performance_tracker.dart
  build_runner/lib/src/generate/phase.dart
  build_runner/lib/src/generate/watch_impl.dart
  build_runner/lib/src/package_graph/apply_builders.dart
  build_runner/pubspec.yaml
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/generate/build_definition_test.dart
  build_runner/test/generate/create_merged_dir_test.dart
  build_runner/test/generate/performance_tracker_test.dart
  build_runner/test/package_graph/apply_builders_test.dart
Labels: cla: yes

#1130 Eagerly find assets matching glob
  build_runner/CHANGELOG.md
  build_runner/lib/src/asset/reader.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1136 Log a warning when pbr serve is used w/o build_web_compilers.
  build_runner/lib/src/entrypoint/options.dart
  build_runner/test/generate/build_integration_test.dart
Labels: cla: yes

#1137 update serialization logic to have separate field enums for node types
  .travis.yml
  bazel_codegen/lib/src/args/builder_options.dart
  bazel_codegen/lib/src/assets/asset_reader.dart
  bazel_codegen/lib/src/assets/asset_writer.dart
  build/.mono_repo.yml
  build/lib/src/asset/reader.dart
  build/lib/src/asset/writer.dart
  build/lib/src/builder/build_step.dart
  build/lib/src/builder/build_step_impl.dart
  build/pubspec.yaml
  build/test/builder/build_step_impl_test.dart
  build_barback/.mono_repo.yml
  build_barback/lib/src/transformer/transformer.dart
  build_barback/lib/src/util/barback.dart
  build_barback/pubspec.yaml
  build_modules/lib/src/kernel_builder.dart
  build_modules/lib/src/module_builder.dart
  build_modules/lib/src/modules.dart
  build_modules/lib/src/summary_builder.dart
  build_modules/lib/src/workers.dart
  build_modules/pubspec.yaml
  build_modules/test/matchers.dart
  build_modules/test/modules_test.dart
  build_runner/lib/src/asset/build_cache.dart
  build_runner/lib/src/asset/cache.dart
  build_runner/lib/src/asset/file_based.dart
  build_runner/lib/src/asset/reader.dart
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/asset_graph/serialization.dart
  build_runner/lib/src/entrypoint/options.dart
  build_runner/lib/src/generate/create_merged_dir.dart
  build_runner/lib/src/server/graph_viz_main.dart
  build_runner/lib/src/server/server.dart
  build_runner/test/asset/cache_test.dart
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/common/common.dart
  build_runner/test/common/in_memory_writer.dart
  build_runner/test/generate/build_definition_test.dart
  build_runner/test/generate/build_integration_test.dart
  build_runner/test/generate/watch_integration_test.dart
  build_test/lib/src/assets.dart
  build_test/lib/src/in_memory_reader.dart
  build_test/lib/src/in_memory_writer.dart
  build_test/lib/src/matchers.dart
  build_test/lib/src/multi_asset_reader.dart
  build_test/lib/src/package_reader.dart
  build_test/lib/src/test_bootstrap_builder.dart
  build_test/lib/src/test_builder.dart
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/lib/src/dev_compiler_bootstrap.dart
  build_web_compilers/lib/src/dev_compiler_builder.dart
  build_web_compilers/pubspec.yaml
  e2e_example/test/common/utils.dart
  scratch_space/test/scratch_space_test.dart
Labels: cla: yes

#1122 Add validation to builder keys
  build_runner/CHANGELOG.md
  build_runner/lib/src/logging/std_io_logging.dart
  build_runner/lib/src/package_graph/apply_builders.dart
  build_runner/lib/src/validation/config_validation.dart
  build_runner/pubspec.yaml
  build_runner/test/generate/build_integration_test.dart
Labels: cla: yes

#1139 Print terse stack traces for uncaught errors
  build_runner/bin/build_runner.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1140 Handle AssetIds with invalid URI characters
  build/CHANGELOG.md
  build/lib/src/asset/id.dart
  build/pubspec.yaml
  build/test/asset/id_test.dart
  build_runner/test/asset/id_test.dart
Labels: cla: yes

#1141 Bump scratch_space SDK constraint
  scratch_space/pubspec.yaml
Labels: cla: yes

#1143 Add PostProcessBuilders
  build_config/CHANGELOG.md
  build_config/README.md
  build_config/lib/build_config.dart
  build_config/lib/src/build_config.dart
  build_config/lib/src/parse.dart
  build_config/pubspec.yaml
  build_config/test/build_config_test.dart
  build_runner/CHANGELOG.md
  build_runner/lib/build_runner.dart
  build_runner/lib/src/asset/reader.dart
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/asset_graph/node.dart
  build_runner/lib/src/asset_graph/serialization.dart
  build_runner/lib/src/build_script_generate/build_script_generate.dart
  build_runner/lib/src/builder/post_process_build_step.dart
  build_runner/lib/src/builder/post_process_builder.dart
  build_runner/lib/src/builder/run_post_process_builder.dart
  build_runner/lib/src/generate/build_definition.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/lib/src/generate/create_merged_dir.dart
  build_runner/lib/src/generate/exceptions.dart
  build_runner/lib/src/generate/performance_tracker.dart
  build_runner/lib/src/generate/phase.dart
  build_runner/lib/src/generate/watch_impl.dart
  build_runner/lib/src/package_graph/apply_builders.dart
  build_runner/pubspec.yaml
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/generate/build_definition_test.dart
  build_runner/test/generate/create_merged_dir_test.dart
  build_runner/test/generate/performance_tracker_test.dart
  build_runner/test/package_graph/apply_builders_test.dart
  e2e_example/build.post_process.yaml
  e2e_example/lib/hello.txt
  e2e_example/pkgs/provides_builder/build.yaml
  e2e_example/pkgs/provides_builder/lib/builders.dart
  e2e_example/pkgs/provides_builder/pubspec.yaml
  e2e_example/test/build_integration_test.dart
  e2e_example/test/common/utils.dart
  e2e_example/test/generated_script_integration_test.dart
  e2e_example/test/goldens/generated_build_script.dart
Labels: cla: yes

#1145 Add some post process builder tests
  build_runner/lib/src/asset_graph/graph.dart
  build_runner/lib/src/asset_graph/node.dart
  build_runner/lib/src/asset_graph/serialization.dart
  build_runner/lib/src/generate/build_impl.dart
  build_runner/test/asset_graph/graph_test.dart
  build_runner/test/builder/run_post_process_builder_test.dart
  build_runner/test/common/builders.dart
  build_runner/test/common/common.dart
  build_runner/test/common/matchers.dart
  build_runner/test/generate/build_test.dart
  build_runner/test/generate/watch_test.dart
Labels: cla: yes

#1146 Ordering and place-holders in README, sym-link LICENSE
  LICENSE
  README.md
Labels: cla: yes

#1147 Add dart2js deferred loading support
  build_web_compilers/CHANGELOG.md
  build_web_compilers/build.yaml
  build_web_compilers/lib/build_web_compilers.dart
  build_web_compilers/lib/builders.dart
  build_web_compilers/lib/src/archive_extractor.dart
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/lib/src/web_entrypoint_builder.dart
  build_web_compilers/pubspec.yaml
  build_web_compilers/test/dart2js_bootstrap_test.dart
  e2e_example/build.dart2js.yaml
  e2e_example/build.post_process.yaml
  e2e_example/build.throws.yaml
  e2e_example/build.yaml
  e2e_example/test/dart2js_integration_test.dart
  e2e_example/test/goldens/generated_build_script.dart
  e2e_example/test/hello_world_deferred_test.dart
  e2e_example/test/serve_integration_test.dart
  e2e_example/web/main.dart
Labels: cla: yes

#1149 release build_config
  build_config/CHANGELOG.md
  build_config/pubspec.yaml
Labels: cla: yes

#1150 release build_runner
  build_runner/CHANGELOG.md
  build_runner/pubspec.yaml
Labels: cla: yes

#1160 Publish build_web_compilers
  build_web_compilers/CHANGELOG.md
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1161 Add missing dep on glob package
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1162 Drop -dev
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1158 Improve the layout of /$perf, especially when resized
  build_runner/CHANGELOG.md
  build_runner/lib/src/server/server.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1165 Use log labels which all have the same width
  build_runner/lib/src/logging/std_io_logging.dart
Labels: cla: yes

#1166 Fix link "getting started guide"
  build_runner/README.md
Labels: cla: yes

#1168 Revert "Use log labels which all have the same width (#1165)"
  build_runner/lib/src/logging/std_io_logging.dart
Labels: cla: yes

#1172 Pass --use-old-frontend to dart2js
  build_web_compilers/CHANGELOG.md
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1173 Update dev dependencies in build_modules
  build_modules/pubspec.yaml
Labels: cla: yes

#1180 Use new frontend with Dart2Js
  build_web_compilers/CHANGELOG.md
  build_web_compilers/lib/src/dart2js_bootstrap.dart
  build_web_compilers/pubspec.yaml
  scratch_space/CHANGELOG.md
  scratch_space/lib/src/util.dart
  scratch_space/pubspec.yaml
  scratch_space/test/scratch_space_test.dart
  scratch_space/test/util_test.dart
Labels: cla: yes

#1190 Exit with an error if a nonexistent command is attempted
  build_runner/CHANGELOG.md
  build_runner/bin/build_runner.dart
  build_runner/lib/src/entrypoint/options.dart
Labels: cla: yes

#1191 Prepare to publish build_web_compilers
  build_web_compilers/pubspec.yaml
Labels: cla: yes

#1176 Fixed typo
  docs/getting_started.md
Labels: cla: no

#1195 Update --output if source with no outputs changes
  build_runner/CHANGELOG.md
  build_runner/lib/src/generate/create_merged_dir.dart
  build_runner/test/generate/watch_integration_test.dart
Labels: cla: yes

#1203 Drop dependency on analyzer
  build_runner/pubspec.yaml
Labels: cla: yes

#1204 A couple more lints - new as of -dev.41
  analysis_options.yaml
  bazel_codegen/lib/src/summaries/build_asset_uri_resolver.dart
  build_resolvers/lib/src/resolver.dart
  build_runner/lib/src/watcher/asset_change.dart
  build_test/lib/src/stub_reader.dart
Labels: cla: yes

#1210 Drop .js.deps file
  build_runner/lib/src/server/graph_viz_main.dart.js.deps
Labels: cla: yes

#1212 Update compiled version of graph_viz_main
  build_runner/lib/src/server/graph_viz_main.dart.js
  build_runner/lib/src/server/graph_viz_main.dart.js.map
Labels: cla: yes

#1213 Include phase number in inspect output
  build_runner/bin/graph_inspector.dart
Labels: cla: yes

#1208 Catch exceptions and mark builds as failures
  build_runner/CHANGELOG.md
  build_runner/lib/src/generate/build_impl.dart
  build_runner/pubspec.yaml
Labels: cla: yes

#1216 PackageNode: normalize paths
  build_runner/lib/src/package_graph/package_graph.dart
  build_runner/test/package_graph/package_graph_test.dart
Labels: cla: yes

#1225 Don't ignore DDC cast failures by default
  build_web_compilers/CHANGELOG.md
  build_web_compilers/lib/src/dev_compiler_bootstrap.dart
  build_web_compilers/pubspec.yaml
Labels: cla: yes
